LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := ARStickersMod
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := ARStickers_All_Pack_V1.5build-1.3.180720036.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
include $(BUILD_PREBUILT)
